apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - lgtm.yaml

secretGenerator:
  - name: otel-config
    envs:
      - otel.sops.env
  - name: github-oauth-secret
    envs:
      - github-oauth.sops.env
