# Kustomization for Container Registry
# Zot 컨테이너 레지스트리 컴포넌트의 리소스를 통합 관리
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: container-registry

resources:
  - namespace.yaml
  - configmap.yaml
  - zot.yaml

generators:
  - ksops-generator.yaml