apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - 00-crd.yaml
  - 10-rbac.yaml
  - 20-deployment.yaml
  - 30-configmap.yaml
  - 40-imageupdater.yaml

generators:
  - ksops-generator.yaml
