# Kustomization for Image Manager
# ArgoCD Image Updater 컴포넌트의 리소스를 통합 관리
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - 10-rbac.yaml
  - 20-deployment.yaml
  - 30-configmap.yaml

generators:
  - ksops-generator.yaml