apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager
  - ingress-nginx
  # - monitoring  # lgtm 비활성화
  - external-secrets
  - container-registry
  # - gateway  # TODO: 설정 완료 후 활성화
  - uptime-kuma
