apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager
  - coredns
  - ingress-nginx
  # - monitoring  # lgtm 비활성화
  - external-secrets
  - image-manager
  - container-registry
  - gateway
  - uptime-kuma
