# ArgoCD 설정 Kustomization
# GitHub OAuth, RBAC, Notifications 설정 관리

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  - argocd-notifications-cm.yaml

generators:
  - ksops-generator.yaml
