apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
- 00-namespace.yaml
- 10-rbac.yaml
- 20-controller.yaml
- 30-ingressclass.yaml
- 40-admission.yaml

# commonLabels는 selector도 변경하므로 사용하지 않음
# ArgoCD가 자동으로 app.kubernetes.io/instance 레이블 추가
