# nonk8s
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # cert-manager v1.16.3 (Gateway API 지원)
  - https://github.com/cert-manager/cert-manager/releases/download/v1.16.3/cert-manager.yaml
  # ClusterIssuers
  - cluster-issuer.yaml       # [Deprecated] NGINX Ingress용 HTTP-01
  - gateway-issuer.yaml       # [Deprecated] Gateway API용 HTTP-01
  - dns-issuer.yaml           # DNS-01 (Cloudflare, 향후 Route53 추가)

generators:
  - ksops-generator.yaml

patches:
  # Gateway API feature gate 활성화
  - target:
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --feature-gates=ExperimentalGatewayAPISupport=true
